### ISSUE TITLE
jQuery.browser is undefined

### ISSUE THREAD

**Issue by inorbita** [pupunzi/jquery.mb.vimeo_player#10]
Hi,

I receive this error and the script won't work. I found jQuery.browser has been deprecated since jQuery 1.9, do you plan on updating the code?

Edit: I'm using jQuery 1.12.4 (Wordpress)

**Comment by pupunzi** [comment]
Hi,
The vimeo_player plug-in uses a redefined jQuery.browser function (jquery.mb.browser.min.js) and it work fine with the latest jQuery framework. 
You're probably using the "jquery.mb.vimeo_player.src.js" file instead of the "jquery.mb.vimeo_player.js" you can find in the "dist" folder; this one contains all the required javascript included the jquery.mb.browser.js.

**Comment by inorbita** [comment]
Ah it works, thanks a lot! I was indeed using the src version.
