### ISSUE TITLE
Player containing div is not visible on player init however the videos are playing hidden

### ISSUE THREAD

**Issue by adam-jones-net** [pupunzi/jquery.mb.vimeo_player#30]
I have the plugin 99% working however it seems that the containing div I reference when I set it up is set to have display:none.   

There are a lot of style attributes in the containing div that are being added to the DOM via Javascript and apparently the vimeo_player.   The container appears to have all the following defined:

`background-image: none; background-position: center center; background-repeat: no-repeat; background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; background-size: auto !important; display: none;`

If I manually disable the display:none of the container and also set the vimeo iframe to a width/height that is anything other than 0px (which is what it is defined at on player init), then I see the video playing.

**Comment by pupunzi** [comment]
do you have a link where I can see your issue?

**Comment by adam-jones-net** [comment]
Hi thanks for your time.  Yes sure, I've made a really stripped back sample page to remove a lot of the complexities of my real implementation.  Again in this hand written page of HTMl that is very minimal I still see the issue.   

My outer div is not visible and the iframe being created within it has 0px height/width params.

**Comment by pupunzi** [comment]
Your issue is caused by the fact that you are trying to instantiate the player on the same dive where you are defining it.
If you want to initialize it on the same div you should set as containment value: "self" and not the ID of the div. But in this way the video is instantiated as a self-standing chromeless player... 
Anyway I attached a zip file with your sample working.

[test_vimeoPlayer.zip](https://github.com/pupunzi/jquery.mb.vimeo_player/files/6319232/test_vimeoPlayer.zip)

**Comment by adam-jones-net** [comment]
Thanks so much, really appreciated!
